# Generated by Django 2.2 on 2020-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_messages', to='user_app.User'),
        ),
    ]
